---


- name: copy files locally
  hosts: localhost
  gather_facts: no


  tasks:
  - name: ansible copy file locally
    copy:
     src: /var/lib/awx/backups/
     dest: /var/lib/awx/backups/backed-up
    delegate_to: localhost


...
