---


- name: copy files locally
  hosts: localhost  #was 127.0.0.1 previously
  gather_facts: no


  tasks:


  - name: ansible copy file locally
    copy:
     src: /var/lib/awx/backups/
     dest: /var/lib/awx/backed-up
     remote_src: no
    delegate_to: localhost

  - name: Recursively remove directory
    file:
      path: /var/lib/awx/backups/
      state: absent


...
