  
---


- name: fetch ansible tower backup from remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: fetch tower backup
      copy:
        src: /scp-root/ansible-tower/backups/tower-backup-2020-03-14-22:02:45.tar.gz
        dest: /var/lib/awx/backups/tower-backup-2020-03-14-22:02:45.tar.gz
        owner: root
        group: root
        mode: '0600'
        remote_src: yes
        force: no

...
