  
---


- name: fetch ansible tower backup from remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: fetch tower backup
      fetch:
        src: /scp-root/ansible-tower/backups/tower-backup-2020-03-12-23:00:55.tar.gz
        dest: /var/lib/awx/backups/tower-backup-2020-03-12-23:00:55.tar.gz
        

...
