---


- name:
  hosts: localhost
  gather_facts: no
  no_log: false


  tasks:

    - name: Set lb monitor
      local_action:
        nsip: 192.168.0.253
        nitro_user: ansible-api
        nitro_pass: Firetruck1!
        validate_certs: no

        module: citrix_adc_lb_monitor
        state: present


        monitorname: monitor_1
        type: HTTP-INLINE
        action: DOWN
        respcode: ['400']
        save_config: yes


...
