---


- name: add real (a "real" VM or physical node to to load balanced)
  hosts: localhost
  gather_facts: no


  tasks:


    - name: create real
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{  nsip  }}"
        nitro_user: ansible-api
        nitro_pass: Firetruck1!
        validate_certs: no

        state: present

        name: server 9
        ipaddress: 9.9.9.9
        comment: server 9
        save_config: yes


...
