---


- name:
  hosts: localhost
  gather_facts: no
  no_log: false
  save_config: yes


  tasks:

    - name: Set lb monitor
      local_action:
        nsip: 192.168.0.253
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no

        module: citrix_adc_lb_monitor
        state: present


        monitorname: dsl-http-ecv-monitor
        type: HTTP-ECV
        action: 'DOWN'
        send: GET /
        recv: '200'


...
