---


- name: create service group
  hosts: localhost
  gather_facts: no


  tasks:
   
    
    - name: Set up http service with ip members
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: 192.168.0.253 #management IP
        nitro_user: ansible-api
        nitro_pass: Firetruck1!
        
        state: present

        servicegroupname: DSL-servers-service-group
        servicetype: HTTP
        servicemembers:
          mode: exact
          attributes:
            - ip: 192.168.0.180
              port: 80
              weight: 50
            - ip: 192.168.0.187
              port: 80
              weight: 40
            - ip: 192.168.0.174
              port: 80
              weight: 10

        monitor_bindings:
          mode: exact
          attributes:
            - monitorname: dsl-http-ecv-monitor
              weight: 50
            - monitorname: dsl-http-ecv-monitor-2
              weight: 50


...
