---


- name: create vip
  hosts: localhost
  gather_facts: no


  tasks:
    

    - name: Create load balancing vserver bound to servicegroup
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: 192.168.0.253 #management IP
        nitro_user: nsroot
        nitro_pass: nsroot
        validate_certs: no
        state: present

        name: DSL-servers-VIP
        servicetype: HTTP
        ipv46: 192.168.0.69
        port: 80
        timeout: 10
        servicegroupbindings:
            - servicegroupname: DSL-servers-service-group


...
