---


- name: add real (a "real" VM or physical node to to load balanced)
  hosts: localhost
  gather_facts: no
  no_log: false


  tasks:


    - name: create real
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{  nsip  }}"
        nitro_user: ansible-api
        nitro_pass: Firetruck1!
        validate_certs: no

        state: present

        name: server_4
        ipaddress: 4.4.4.4
        comment: yo yo yo


...
