---


- name: add real (a "real" VM or physical node to to load balanced)
  hosts: localhost
  gather_facts: no
  no_log: true


  tasks:


    - name: create real
      delegate_to: localhost
      citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: nsroot
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: server_4
        ipaddress: 4.4.4.4
        comment: yo yo yo


...
