---


- name:
  hosts: localhost
  gather_facts: no
  no_log: true


  tasks:

    - name: Set lb monitor
      local_action:
        nsip: 192.168.0.253
        nitro_user: ansible-api
        nitro_pass: Firetruck1!
        validate_certs: no

        module: citrix_adc_lb_monitor
        state: present


        monitorname: dsl-http-ecv-monitor
        type: HTTP-ECV
        save_config: yes


...
