  
---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: copy nightly backup
      copy:
        src: /scp-root/ansible-tower/tower-backup-2020-03-14-22:02:45.tar.gz
        dest: /root/ansible-tower-setup-3.6.3-1/
        owner: root
        group: root
        mode: '0600'
        remote_src: yes
        force: no

...
