  
---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:
  
  
    #- name: edit permissions to enable copying
      #file: path=/var/lib/awx/backups/ owner=awx group=awx mode=0777 state=directory recurse=yes


    - name: copy nightly backup
      copy:
        src: /scp-root/ansible-tower/
        dest: ansible-tower-setup-3.6.3-1/
        owner: root
        group: root
        mode: '0600'
        remote_src: yes
        force: no

...
