---


- name: rdc aci cutover
  hosts: 10.5.0.100


  tasks:


  - name: shut one svi at a time on nxos
    nxos_config:
      config: "{{ lookup('template', 'templates/core-shut-svi.j2') }}"
    become: yes
    become_method: enable


...