  
---

- name python test
  hosts: tower  #localhost
  gather_facts: no

  
  tasks:


  - name: run python script  
    # default Python here
    - shell: echo hello
    #- set_fact:
    #    ansible_python_interpreter: /local/{{lookup('env', 'USER')}}/venv/bin/python
    # modified Python here
   # - shell: echo hello


...
