---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:
  
  
    - name: edit permissions to enable copying
      file: path=/var/lib/awx/backups owner=root group=root mode=0777 state=directory recurse=yes


    - name: copy nightly backup
      copy:
        src: /var/lib/awx/backups/.
        dest: /scp-root/ansible-tower/
        remote_src: no

...
