---


- name: nightly tower backup
  hosts: 127.0.0.1
  gather_facts: no
  become: yes

  tasks:


    - name: backup tower
      shell: /root/ansible-tower-setup-3.6.3-1/setup.sh -e 'backup_dest=/var/lib/awx/backups' -b
      # edit directory name above after every ansible tower upgrade

...
