---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: copy nightly backup
      copy:
        src: /var/lib/awx/backups/.
        dest: /scp-root/ansible-tower/
        owner: root
        group: root
        mode: '0600'
        remote_src: no
        force: no

...
