---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: Copy file with owner and permissions
      copy:
        #src: /var/lib/awx/backups/tower-backup-2020-03-08-23:14:32.tar.gz
        src: /var/lib/awx/backups/.
        dest: /scp-root/ansible-tower/
        owner: root
        group: root
        mode: '0644'
        remote_src: no

    - name: empty the backup directory so as to only copy necessary files next run
      shell: cd /var/lib/awx/backups && find -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf --
...
