---


- name: edit file permissions to enable Ansible to copy backup file owned by root
  hosts: localhost
  gather_facts: no
  become: yes


  tasks:


    - name: edit permissions
      file: path=/var/lib/awx/backups/ owner=awx group=awx mode=0777 state=directory recurse=yes


...
