---


- name: copy nightly tower backup to remote server
  hosts: 192.168.0.192
  gather_facts: no
  become: yes


  tasks:


    - name: Copy file
      copy:
        src: /root/ansible-tower-setup-3.6.0-1/tower-backup-2020-03-08-20:38:47.tar.gz
        dest: /scp-root/ansible-tower/
        remote_src: no

...
